### ISSUE TITLE
Citizens Causing TAB to Bug Out

### ISSUE THREAD

**Issue by InfinityAspire** [CodeCrafter47/BungeeTabListPlus#10]
Standing near statues created by citizens causes the TAB list to bug out.
![viegz4w](https://cloud.githubusercontent.com/assets/9050130/5911895/d5656060-a5c3-11e4-88b6-3437afea7d29.png)

I know the devs of citizens are working on getting citizens removed from TAB lists and they have already succeeded with the Vanilla 1.8 TAB list. Perhaps you could work with the devs of that plugin.

**Comment by CodeCrafter47** [comment]
I think this needs to be fixed in citizens. If citizens stops sending tablist packets for citizens, those bugs will disappear.
This is probably difficult/ impossible because the citizens will be invisible if there are not tablist packets sent for them. It happens because of the way mojang changed the tablist in 1.8. That also prevents BungeeTabListPlus from removing the playerskins on the bottom right, see #13 and #1.
