### ISSUE TITLE
Suspecting Memoryleaks

### ISSUE THREAD

**Issue by EMC3** [CodeCrafter47/BungeeTabListPlus#111]
Hello,

As i am experiencing MemoryLeaks, i repoted it to bungee, but as one of the 3 plugins installed is yours i'm opening this issue. For further information see https://github.com/SpigotMC/BungeeCord/issues/1888#issuecomment-226702746

**Comment by CodeCrafter47** [comment]
As far as I know there are no memory leaks in BungeeTabListPlus.

However using (bad) plugins such as FeatherBoard, AnimatedNames or the like can increase the amount of memory required per player.

It might also be interesting to know which version of BungeeTabListPlus you are using.

**Comment by EMC3** [comment]
I do not use any of rhese plugins. i'm using the latest version of bungeetablistplus. btw don't you think that 60Mb per player are a bit too much?

**Comment by andrewkm** [comment]
Spigot 880 BungeeTabListPlus 510 and Bungee 1159
Can confirm this plugin leaks like all hell on 1.10
Examined with YourKit.

Removed it and all issues gone.
Doesn't matter how much memory you give bungee (I've tested with major amounts and only 150 player instances), after enough time on a big server bungee gets trashed with direct buffer memory problems and dumps all players.

Removed this plugin and absolutely all issues fixed.

**Comment by CodeCrafter47** [comment]
Build 501 to 511 have an issue that can cause the plugin to send some unnecessary packets which can lead to increased memory usage. That issue has been introduced with 49f2c089fa4ec90d4b1ff70dadb28b1991d42a6f and fixed with 325aae303aa06223793cb4a59d28d59700a93c6a. However the only point where I've seen that causing bungee to crash because of out of memory was when using a very high update rate for the tab list (update it like every 0.02 milliseconds) where it would send the header again even if it was not changed. Version 2.4.5 of the plugin is not affected by this issue.

In one of the screenshots @EMC3 provided it can be seen that there are 491901 instances of net.md_5.bungee.api.score.Team. With 23 player online this means each player has a scoreboard with ~20000 teams which also require a lot of memory. This is also the reason why I initially mentioned FeatherBoard and AnimatedNames as these plugins are known to create a lot of teams. Also they save the teams in the persistent scoreboard, so the teams will still be there even if you delete the plugin. You can look at the size of scoreboard.dat to see whether that is causing the issue.

**Comment by andrewkm** [comment]
Bungee doesn't crash, but prevents players from joining until it's restart due to direct buffer memory.

**Comment by andrewkm** [comment]
@CodeCrafter47 Also, my scoreboard.dat is 208 bytes. (So basically tiny).

**Comment by andrewkm** [comment]
sorry for yet another post, just want to 1000% confirm (as opposed to 100%) that the memory leak in bungee is absolutely related to this plugin. (Or perhaps "was" now after your latest fix).

I am now testing 512 and will report back, but am now certain, after having my team look into all the servers we run, timestamps, etc, when it all began and all. 100% this plugin.

**Crossing fingers that 512 has it fixed**
Will report back within 24-48 hours.

**Comment by CodeCrafter47** [comment]
Thinking of it now, I think there's probably a buffer leak also introduced with build 501.

**Comment by CodeCrafter47** [comment]
There definitely is, netty shows it (using -Dio.netty.leakDetectionLevel=paranoid):
```
SCHWERWIEGEND: LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 0
Created at:
    io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:280)
    io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:155)
    io.netty.buffer.UnsafeByteBufUtil.copy(UnsafeByteBufUtil.java:255)
    io.netty.buffer.PooledUnsafeDirectByteBuf.copy(PooledUnsafeDirectByteBuf.java:229)
    io.netty.buffer.SlicedByteBuf.copy(SlicedByteBuf.java:150)
    io.netty.buffer.AbstractByteBuf.copy(AbstractByteBuf.java:943)
    io.netty.buffer.WrappedByteBuf.copy(WrappedByteBuf.java:699)
    io.netty.buffer.AdvancedLeakAwareByteBuf.copy(AdvancedLeakAwareByteBuf.java:672)
    net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:24)
    net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
    io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
    io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
    io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
    io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
    io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
    io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    java.lang.Thread.run(Thread.java:745)

09:14:37 [SCHWERWIEGEND] Jun 18, 2016 9:14:37 AM io.netty.util.ResourceLeakDetector reportLeak
SCHWERWIEGEND: LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 0
Created at:
    io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:280)
    io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:155)
    io.netty.buffer.UnsafeByteBufUtil.copy(UnsafeByteBufUtil.java:255)
    io.netty.buffer.PooledUnsafeDirectByteBuf.copy(PooledUnsafeDirectByteBuf.java:229)
    io.netty.buffer.SlicedByteBuf.copy(SlicedByteBuf.java:150)
    io.netty.buffer.AbstractByteBuf.copy(AbstractByteBuf.java:943)
    io.netty.buffer.WrappedByteBuf.copy(WrappedByteBuf.java:699)
    io.netty.buffer.AdvancedLeakAwareByteBuf.copy(AdvancedLeakAwareByteBuf.java:672)
    net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:24)
    net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
    io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
    io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:354)
    io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
    io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
    io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
    io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    java.lang.Thread.run(Thread.java:745)
```

cc14a50af2de570c334a26f742eda890b2ba3e88 fixes it.

**Comment by andrewkm** [comment]
512 is fucked as well, just crashed all players with direct buffer memory once again.

Not willing to test further until after the weekend (weekends are our peak times with many events)

But yeah 512 is dead.

I see you made more changes, I'll test starting Monday on those.

**Comment by andrewkm** [comment]
Been insanely busy all weekend, just loading up 519 now (had plugin removed through weekend), and will let it run through.
Will respond with results after 24-48 hours. (Usually crashes after 5-8 on previous builds)

**Comment by EMC3** [comment]
I had no crashes with the latest version, well done.
I do not know if there are still leaks, but if there are, they have been reduced. Maybe i have another leaky plugin because i think that 1.5G usage with 50 players is still too much. As soon there are less players online i will do another dump....

**Comment by EMC3** [comment]
Today i got another crash with the latest version of bungeetablistplus. This time i extracted following informations out of a heapdump:

1. codecrafter47.bungeetablistplus.tablisthandler.logic.TabListLogic takes 220 MB
2. Someone keeps 500 Mb of strings. The majority of strings splits 50/50 to the string "always" and uuids

**Comment by CodeCrafter47** [comment]
That's not a leak. The data is cleaned up when the player leaves the server.

The memory is required to store the scoreboard, so it can be cleared when the player switches the server. Also BungeeTabListPlus requires the scoreboard data to work. Usually the server scoreboard should not use that much memory, but some bad plugins (like FeatherBoard, AnimatedNames, Citizens) fill the scoreboard with teams they do not use. This not only increases the memory requirement of BungeeCord but also causes increased load times for players.

You can check the scoreboard.dat file and remove it if it is more than a few kb in size. That will fix the issue, at least until it grows again.

You can also start BungeeCord with the `-XX:+UseStringDeduplication` java flag, which will reduce the memory required for duplicate strings at the cost of slightly increased cpu usage.

I don't think it is my responsibility to fix this issue. It happens because of bad or incorrectly configured bukkit plugins and due to the way BungeeCord stores the scoreboard data. Removing BungeeTabListPlus will only slightly reduce the memory usage as BungeeCord will still keep the scoreboard data.

**Comment by andrewkm** [comment]
Memory leak has not shown itself for two consecutive 24 hour up times. (I'm back to my original small 1G bungee Xmx)

Leaving this current up time to go for three days to be absolutely certain, but from initial tests and observations this issue seems fixed.

Will reply again if you wish after this very long planned (48h+) up time.

**Comment by andrewkm** [comment]
@CodeCrafter47 I am 95% positive (if not certainly) that this memory leak issue has been fixed.
Should issues arise in the future I will respond here again, but I'm quite sure that this is now fixed after further testing and memory usage examination.

Thank you for your help! :)

**Comment by CodeCrafter47** [comment]
@EMC3 Are you still experiencing high memory usage with version 2.5.1 of the plugin?

**Comment by EMC3** [comment]
i will try tomorrow. Maybe it would help if you stop catching out of memory errors so bungee crashes and dumps instead of hanging around waiting for someone to kill it manually...
