### ISSUE TITLE
Player head

### ISSUE THREAD

**Issue by ghost** [CodeCrafter47/BungeeTabListPlus#133]
When I set default head, couple heads depending on number of players online shows heads of these players, not my default.

**Comment by CodeCrafter47** [comment]
See #13 and #1 

Only way to fix it is to either set the size of the tab list to 80 or make sure _all players on the same server as the player viewing the tab list_ are displayed on the tab list.

**Comment by CzlowiekKuktas** [comment]
Well, all players on the servers are displaying the same tablist.

**Comment by CodeCrafter47** [comment]
That's not the point.

Let's assume there is a lobby server and a survival server. Now I'm being connected to the lobby server along with two other players. Since the three of use are on the same server, for each of us three one icon in my tab list must display the respective skin.

Now if the config file is somehow setup to not display all the players on the same server with you then BungeeTabListPlus will just display the skins of the missing players at random places on the tab list.

**Comment by CzlowiekKuktas** [comment]
Why?

**Comment by CodeCrafter47** [comment]
That's simple. All players on the same server must have their skin somewhere in the tab list. Otherwise there would be severe issues like some players would just be invisible, skins not working correctly, spectators being unable to go through walls.
