### ISSUE TITLE
BungeeTablistPlus - Bukkit

### ISSUE THREAD

**Issue by ghost** [CodeCrafter47/BungeeTabListPlus#136]
Hi, can you add method that will refresh tablist for exact player or players on exact server?

**Comment by CodeCrafter47** [comment]
There's no point in that. The plugin currently refreshes the tab list at least every second which should be fast enough.

Is there any reason why you would want to refresh the tab list more often and especially why you would want to initiate the refresh from a bukkit server?

**Comment by CzlowiekKuktas** [comment]
I want tablist to be refreshed less often, to be more efficient.

**Comment by CodeCrafter47** [comment]
Ok, so an API to request additional refreshes does not achieve this goal, so we can agree that it is not needed.

Concerning the efficiency, I plan on making the plugin more efficient in the future, by only updating the parts of the tab list where the content actually changed instead of updating the entire tab list every second.

**Comment by CzlowiekKuktas** [comment]
If I set refreshing to 10 seconds, and I want something to change faster the refresh method in the bukkit would be great.

**Comment by CodeCrafter47** [comment]
The tab list is updated at least every two per second no matter what you put in the config.

**Comment by CzlowiekKuktas** [comment]
Why?

**Comment by CodeCrafter47** [comment]
Because I plan to move away from the concept of updating the entire tab list at a fixed interval. Some parts need to be updated very often (like animations), some parts don't change at all, and some parts are rarely changed (like the players balance or permission group).

The plugin already updates animations at a higher interval than the rest of the tab list and I'm confident I can make the required changes so it will only update the slots that require to be updated whenever they require to be updated instead of updating the entire tab list at a fixed interval.

**Comment by CzlowiekKuktas** [comment]
Nice. When will this be done? :)

**Comment by CodeCrafter47** [comment]
I hope to add it for the 2.7.0 update.

**Comment by CzlowiekKuktas** [comment]
So when?

**Comment by CodeCrafter47** [comment]
Probably still a few months.

**Comment by CodeCrafter47** [comment]
This took way longer than expected, but with the latest version the tab list is only updated in parts and only if the data that is displayed changes. E.g. when your ping changes the plugin will update the slot displaying your ping.
