### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by TeeKay1** [CodeCrafter47/BungeeTabListPlus#147]
Ok so I have been getting the "update your default file" in the log and I went to and there is nothing i really need to change. Also for some reason I cant get the balance of my players to show. I use Iconomy for my money plugin. Also is there a way to get my admins and mods to have there ranks on the tablist? I use essentials group manager. The server version is 1.10.2 and the version of the tablist is 2.6.4

**Comment by CodeCrafter47** [comment]
You are getting that message because your configuration file has been created before the 2.6.0 update. You need to remove the file and create a new config file based on the instructions on the wiki to ensure your configuration will still work in the future as support for the old configuration files will be removed in a coming update.
