### ISSUE TITLE
AnimatedNames Conflict

### ISSUE THREAD

**Issue by InfinityAspire** [CodeCrafter47/BungeeTabListPlus#15]
It seems that if this plugin is in the BungeeCord server, and AnimatedNames is in the Bukkit servers it affects, this plugin causes AnimatedNames to bug out and apply random groups to players with no permissions. I learned from the author of AnimatedNames that both of these plugins use the scoreboard and after testing, I learned that they both work perfectly well independently of one another. This issue seems to have also been causing the Alex/Steve skin issues.

**Comment by CodeCrafter47** [comment]
I will have a look at that plugin.

**Comment by InfinityAspire** [comment]
Have you had to opportunity to investigate this yet?

**Comment by CodeCrafter47** [comment]
This is a complicated issue since it is connected to the way BungeeTabListPlus tricks 1.8 clients to show a custom tablist without affecting gameplay. I have an idea how to fix it but since it involves rather big changes to the code you shouldn't expect an update on this anytime soon (I will be quite busy with school until end of march).

**Comment by CodeCrafter47** [comment]
Not sure whether that's an improvement, but the latest dev-build of BungeeTabListPlus blocks all scoreboard team packets in order to prevent issues. That prevents AnimatedNames from working thought.
Only exception is when tab_size is set to 80. In that case there shouldn't be any issues(no guarantee, just what I think).

**Comment by Pangamma** [comment]
The code may have changed since this issue was created, but the last two days (since we started setting up animated names) the proxy has been crashing from out of memory errors like five times a day. It used to be able to go for weeks between reboots. So... I guess I'll disable animated names and see if that makes a difference.

**Comment by CodeCrafter47** [comment]
According to someone in the forums the issue with AnimatedNames is fixed: [https://www.spigotmc.org/threads/bungeetablistplus.10325/page-92#post-1390463](https://www.spigotmc.org/threads/bungeetablistplus.10325/page-92#post-1390463)
