### ISSUE TITLE
Received string lenght is longer than maximum allowed (40 > 16)

### ISSUE THREAD

**Issue by DanielAlves123** [CodeCrafter47/BungeeTabListPlus#159]
Hi, I have problems with self-compiled version of BTLP. I didn't change anything, just compiled it, and when i'm trying to join the server with the BTLP tablist on 1.7 client it just kicks me with: 'Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: The received string lenght is longer than maximum allowed (40 > 16)'. Also there are errors in the example plugin, because you can't compile it.

**Comment by CodeCrafter47** [comment]
I can't reproduce the issue.

**Comment by DanielAlves123** [comment]
@CodeCrafter47 the problem still exists.

**Comment by CodeCrafter47** [comment]
I can't fix it unless I can reproduce it. To reproduce it you need to tell me exact steps which will cause this issue to occur. That includes which BungeeCord, Spigot and BungeeTabListPlus version to use and which changes to the default configurations are required to reproduce the issue.

Please not that I won't help if it isn't possible to reproduce the issue without additional plugins (as in that case I must assume that the issue isn't caused by BungeeTabListPlus).

**Comment by DanielAlves123** [comment]
1. I download the project.
2. I change the pom.xml to disable example module, because I can't build it.
3. I change jar files to the generated ones, and this problem occurs for 1.7 players.

**Comment by CodeCrafter47** [comment]
You already mentioned most of that. After you created the issue I tested the plugin with a 1.7 client, I compiled version 2.6.4 and the latest snapshot from git, and both worked fine. Also compiling the example plugin worked fine, though it doesn't really matter whether you build that or not, it's mostly there for reference.

Since I can't think of anything new to try in order to reproduce this issue I've got some more questions:

1. Latest BungeeCord doesn't support 1.7 players. Which version did you use?
2. Same goes for spigot. Which version did you use?
3. Since you got the source from git, which revision (version) did you compile?
4. You said you compiled BungeeTabListPlus yourself. Is that necessary to reproduce the issue or does it also occur when using the builds available on spigotmc or on my jenkins?
5. I assume you used an 1.7.10 client with no mods, is that correct?

**Comment by HAMMERxPL** [comment]
I'm using latest Travertine version. 
Spigot: This server is running CraftBukkit version git-Spigot-7d78b81-056af8b (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
I just downloaded it from the github page.
I just check latest dev-build and everything works good. It happens on self-compiled version.
1.7.10 with and without mods.

**Comment by CodeCrafter47** [comment]
If you download the source again and compile it everything should work fine. Also you should be able to compile the example plugin.
