### ISSUE TITLE
BTLP prevents each server from working with the scoreboard function seeFriendlyInvisibles

### ISSUE THREAD

**Issue by Jackv1999** [CodeCrafter47/BungeeTabListPlus#171]
https://hub.spigotmc.org/jira/browse/SPIGOT-2995 Here is the JIRA issue I created because I thought it was  an issue within spigot itself, but it turns out it was your plugin.

**Comment by CodeCrafter47** [comment]
I know, but this can't be fixed.

Only available work-around is to set the size of the tab list to 80 slots.

**Comment by Jackv1999** [comment]
Why is that a work around, can you explain? It seems a shame to stop using this plugin just because of this  bug.

**Comment by CodeCrafter47** [comment]
When the size of the tab list is below 80 slots BungeeTabListPlus needs to assign a separate scoreboard team to every player in order to be able to order the slots of the tab list.

**Comment by Jackv1999** [comment]
There's no other solution to this apart from not using the plugin?

**Comment by Jackv1999** [comment]
My plugin NoCollide works with BTLP, that also uses teams. Why does the no collision tag work but not see friendly invisibles?

**Comment by CodeCrafter47** [comment]
As I said you can set the size of the tab list to 80 slots. That will fix the problem.

An alternative would be to disable the customized tab list on the server that requires the `seeFriendlyInvisibles` option to work.

Most team options work fine because BungeeTabListPlus copies them from the original team of the player to the one it creates for the player. That way options like prefix, suffix and color continue to work while every player has it's own team which allows BungeeTabListPlus to work correctly.

**Comment by Jackv1999** [comment]
Thanks, I will have to put up with having an oversized tablist, it's better than nothing :) Your plugin is great by the way, and thanks for the fast replies.

**Comment by iFlyinq** [comment]
Just found out that using `size: 80` instead of `columns: x` fixes this while using a row value under 80 makes it buggy again.
