### ISSUE TITLE
vaultGroupInfo not sorting properly

### ISSUE THREAD

**Issue by UberPilot** [CodeCrafter47/BungeeTabListPlus#184]
I've configured a tablist following the columns example, but when I attempt to sort the players based on vaultGroupInfo, it doesn't work. 

![2017-02-12_15 14 15](https://cloud.githubusercontent.com/assets/6300129/22866571/f21adc2a-f135-11e6-8a53-9e72a0036cb3.png)

The players on this list should be flipped as the rank UberPilot has is at rank 1, and the rank SuperPilot99 has is at rank 1100 using PermissionsEx, Vault and with the bridge installed. 

Tablist File:
https://hastebin.com/yoniqulumo.yml

Config:
https://hastebin.com/muyuluvime.yml

**Comment by CodeCrafter47** [comment]
You should preferably use the `weight` property, not the `rank` property to order groups, as PEX uses the `weight` property to determine the primary group, whereas the `rank` property is used to determine the order of groups within the same ladder for the promote/ demote commands. If the `weight` property is set for all groups then BungeeTabListPlus can order them correctly.

However not all permission plugins use a `weight` property, some only have the `rank` property, so in cases where BungeeTabListPlus can't find the `weight` property (because either it is not set or the permission plugin doesn't support it) it will fall back to using the `rank` property instead.

When using PermissionsEX setting the `weight` property for all groups is recommended. The players will be ordered correctly then.

If the order of the players is reversed, you can use `vaultGroupInfoReversed` instead of `vaultGroupInfo` to fix it. This shouldn't be required when using PermissionsEx, but some other plugins do the rank numbers the other way round.
