### ISSUE TITLE
/btlp fake add - broken

### ISSUE THREAD

**Issue by MithrandirCraft** [CodeCrafter47/BungeeTabListPlus#195]
/btlp fake add <name>
Does not work at all. Ingame, you get a message saying that you don't have permission. On console, the command isn't even identified.
I'm reporting this because this command is displayed on the wiki documentation.

BTLP v 1.7.6
Spigot for MC: 1.11.2

**Comment by CodeCrafter47** [comment]
As stated on the wiki you need the `bungeetablistplus.command` and `bungeetablistplus.admin` permissions. The permissions should be given on BungeeCord. Having the permissions on Spigot is not sufficient.

The command can be executed from the BungeeCord console. It does not work from the Spigot console (because Spigot doesn't know about BungeeCord plugins and their commands).

**Comment by MithrandirCraft** [comment]
Well. At the moment, fromthe Bungee Console, the command returns "not found". All my staff has tried it.
As for the permissions. I'm testing that now.

**Comment by MithrandirCraft** [comment]
Solved, thanks.
