### ISSUE TITLE
PlayerOrder by custom variable

### ISSUE THREAD

**Issue by JamieSinn** [CodeCrafter47/BungeeTabListPlus#221]
Would it be possible to have the playerorder be sorted by the custom variables?

It'd work (for us at least) just like the vaultPrefix variable right now, as we create a custom variable to show a rank prefix.

Thanks.

**Comment by Foorack** [comment]
Very interested in this. :+1:

**Comment by CodeCrafter47** [comment]
This currently lacks a proposal how it should look in the config file. I'd appreciate some suggestions towards that end, as once that is decided it should be fairly easy to implement.

**Comment by Foorack** [comment]
@CodeCrafter47 I would mostly be interested in an option for plugings to register custom SortingRule's, similar to registering placeholders. https://github.com/CodeCrafter47/BungeeTabListPlus/blob/bd64016e70c3571ff1eee9b65f30cf8e04e3e9a1/bungee/src/main/java/codecrafter47/bungeetablistplus/playersorting/SortingRuleRegistry.java#L28

**Comment by CodeCrafter47** [comment]
I'm a bit skeptical towards that. Being able to sort players by the value of an arbitrary placeholder should cover most (probably all) use cases and is easier to implement. Exposing sorting rules through the API may prevent optimizations in that part of the plugin.

**Comment by Foorack** [comment]
That is true. :confused: Well in our case we are using LuckPerms and we have two tracks. Track A should take priority. If two players are in the same place on track A then those two should be ordered according to track B. Would that be possible to achieve if this was implemented as a config option?

**Comment by CodeCrafter47** [comment]
I think so. Currently it is possible to combine multiple sorting rules. For example one can sort by server and the players on the same server by name. It's explained in the wiki: <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PlayerOrder>.

**Comment by Foorack** [comment]
@CodeCrafter47 I cannot find the option to give arguments to a SortingRule. On our server we want players to first be sorted by the LP track "rank" (a track is similar to a PEX ladder), and then sorted by the second track "donator". AFAIK this is not possible with the current system. :confused:

**Comment by Foorack** [comment]
@CodeCrafter47 With reflection (ouch) I was able to inject a custom SortingRule and that fixed it. Having a public API would be great. A more generalized example-use-case is if a server wants to sort players depending on their position in a minigame.

**Comment by CodeCrafter47** [comment]
This issue is about sorting the players by a custom variable. That can most certainly be implemented. You're right, currently there is no way to pass any arguments to a SortingRule, however that, too, can be implemented. The actual implementation in Java code should be quite simple, what I'm more worried about is, how these sorting rules will look in the config file.

The design of the config file must take into account the following points:

 - The config file should be ease to read and write
 - Sorting rules need to be chainable
 - It should be possible to reverse the order (e.g. differentiate between ascending, descending order)
 - It may need to be possible to specify whether the variable replacement is to be interpreted as number or text. While the plugin may know what kind of data a placeholder holds for the built-in ones, it doesn't know for those from PlaceholderAPI or for custom ones
 - The may need to be possible to sort the players in a way that the players for whom the variable resolves to the same symbol as for the player looking at the tab list appear first(similar to the `playerServerFirst` sorting rule)

Some design ideas I've come up with so far are

1. Allow users to just write placeholders in place of a sorting rule, for example
   ```yaml
   playerOrder: ${player health}
   ```
   While this is very simple it doesn't meet with a lot of the other criteria. However a bonus point is, that it fits right into the existing scheme.
2. Use what programming language engineers might call constructors, not quite sure about the actual design, but the following seem quite nice
   ```yaml
   playerOrder: ascending(health)
   ```
   or possibly 
   ```yaml
   playerOrder: health ascending
   ```
   This design is still pretty simple and fits the existing scheme, but potentially allows for a bit more information to be passed to the SortingRule than the first idea, thus allowing to differentiate ascending and descending order, possibly also adding other information.
3. Make use of yaml's tags
   ```yaml
   playerOrder: !by_placeholder
     placeholder: ${player health}
     order: ascending
   ```
   Here the advantage is, that by using named parameters lot's of options may be passed to the SortingRule. Also using tags is in line with other parts of the plugins (i.e. component configuration). Though it might make the config more complicated and doesn't fit with what is already there.

These are just my thoughts, feel free to comment on them or present your own. Doesn't need to be prefect, none of my ideas is.


So sorting players by arbitrary placeholders it something I eventually want to implement. I think this can benefit more people than a Java API, as it's more accessible (Don't need to know Java). Also the PlayerSet and SortingRule code is subject to change in near future. Currently it's very inefficient, sorting all players many times per second, while it would be sufficient to keep a sorted list of the players and update it when necessary. With these changes ahead I think it's a bad time to create an API now, and after these changes SortingRule's will probably be way more difficult to implement, so not sure anyone would use an API then.

**Comment by BijuuKrunos** [comment]
Heyho its 1 and a half year later, just wanted to ask if that is still comming? xD
I would like that afk players are listed at the end. I am using a self coded AFK-Plugin wich placeholderapi integration. As I know the Playerorder afklast is for essentials only (didn't find any information about this) so it won't be usable with my afk plugin. could a simple yes or no api or config be implemented? not with hearts just with boolean placeholders like "is he afk? yes or no". Just something super simple?

love this plugins <3

**Comment by CodeCrafter47** [comment]
This is still planned. It is not going to happen soon though.

**Comment by CodeCrafter47** [comment]
It is now possible to sort players by any placeholder. Have a look at <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PlayerOrder>.
