### ISSUE TITLE
Sponge Bridge not working [2.7.4] Players are unable to join

### ISSUE THREAD

**Issue by i9hdkill** [CodeCrafter47/BungeeTabListPlus#227]
When using 2.7.4 on Bungee and 2.7.4 on sponge 1.10.2, players are unable to join the sponge server
Error: https://pastebin.com/ZjqWj5iP

Hm, on bukkit it's fine but viewer vault_currency_plural is missing. That could be the issue.
Bungee: 1.12
It worked on a bungee 1.11 + 2.6.4

**Comment by CodeCrafter47** [comment]
I just tested it and did not experience any crash using BTLP 2.7.4 on Bungee(1.12) and Sponge(1.10.2).

Please make sure you are really running version 2.7.4 of BTLP on BungeeCord. The error you experienced is in most cases caused by running version 2.7.x on Sponge and an older version on BungeeCord.

**Comment by i9hdkill** [comment]
Yes, I double checked that.
Can you check with this tablist config?
https://pastebin.com/sYw7W1wx

+ an installed economy plugin on sponge?

**Comment by CodeCrafter47** [comment]
I just checked with that config and an economy plugin (EconomyLite). I was able to connect to the sponge server just fine. Currency name didn't show up though.

**Comment by CodeCrafter47** [comment]
I think I just fixed this issue.

89159473a6ddd57e9cda897635e1a33a8122f520 fixes players being kicked.
bd64016e70c3571ff1eee9b65f30cf8e04e3e9a1 fixes the currency placeholders.

All available as part of the latest [dev-build](http://ci.codecrafter47.de/job/BungeeTabListPlus/).
