### ISSUE TITLE
Suggestions / Bugs

### ISSUE THREAD

**Issue by CryptoMorin** [CodeCrafter47/BungeeTabListPlus#251]
Doesn't ${viewer skin} support SkinsRestorer?

Do we have any placeholder which defines the server version like... ${viewer server_version} just like ${viewer client_version}

Is there any ${server_max_player_count} so we can use it next to ${server_player_count}?

Is there any ${playerset:global max_size} so we can use it next to ${playerset:global size}?

Is there any ${viewer hunger} and ${viewer max_hunger} ?

Are there any 
${viewer location_x2}
${viewer location_y2}
${viewer location_z2}
so the number wont get too long?

(Sorry if this is the wrong place for posting this)

**Comment by CodeCrafter47** [comment]
> Doesn't ${viewer skin} support SkinsRestorer?

Yes, however the Minecraft client only displays the icons in the tab list if connected to an online mode server. You can use a plugin like [FastLogin](https://www.spigotmc.org/resources/fastlogin.14153/) to enable online mode for players with a valid copy of Minecraft while still allowing cracked players to join (cracked players never see the icons).

> Do we have any placeholder which defines the server version like... ${viewer server_version} just like ${viewer client_version}

There is no such placeholder.

> Is there any ${server_max_player_count} so we can use it next to ${server_player_count}?

There is no max player count placeholder. However as the maximum doesn't change you can just type in the number that is your maximum player count as text. 

> Is there any ${playerset:global max_size} so we can use it next to ${playerset:global size}?

Same as above.

> Is there any ${viewer hunger} and ${viewer max_hunger} ?

You need to install PlaceholderAPI and BungeeTabListPlus_BukkitBridge on the Bukkit/ Spigot server. Then you can use `${viewer player_food_level}`. There is no placeholder for the maximum. However the maximum is 20, so you can just type that in.

> Are there any
> ${viewer location_x2}
> ${viewer location_y2}
> ${viewer location_z2}
> so the number wont get too long?

`${viewer location_x 1.2}`, `${viewer location_y 1.2}` and `${viewer location_z 1.2}`.

**Comment by CryptoMorin** [comment]
But can it just display the skin name... I mean the premium skin name which the player used.

Like /skin test
It should show the "test" name with the icon.

Anyway I know these placeholders can be manually done but it's just a little hard to change it Everytime you update...

Thanks for the hunger bar and XYZ.

+
Just having a really bad problem with the components. I know it's not the plugin problem but it's just confusing... Making a good tablist isn't really easy...

Honestly the hardest config not considering how long it is... How smart you have to be to make a good shit out of it... Is this plugin.
However I know it's advanced and you have to read the wiki several times but I still have some personal questions that I want to ask.

When I got my PC back I'll make a list.
Btw... Thanks for the fast support :P

**Comment by CryptoMorin** [comment]
Hi there,
I did make a list from all i don't really know, Please read till the end when you had time.

1. Can you add the premium skin name to ${viewer skin} so it'll show the name as well...

2. As we have ${viewer health} / ${viewer max_health} you should add ${viewer hunger} ${viewer max_hunger} as well... (${viewer player_food_level} doesn't work...)

3. ${viewer vault_balance} should be ${viewer vault_balance1} as the normal balance is without decimals. So more numbers more decimals. as Essentials allows more. E.g. ${viewer vault_balance} = $10 ${viewer vault_balance 1} = $10.0 ${viewer vault_balance 2} = $10.00 And.. etc (Btw... as you have {viewer location_x 1} and the "1" have space between the "location_x" you should change it that ${viewer vault_balance1} must be ${viewer vault_balance 1}

4. When "serverSeparator" is empty without any text lines it still displays an empty slot between each servers.

5. What's the difference between "customplaceholders" in configuration file and the one in tablist config file? Does the one in the main config work 1 for all the tablists?

6. How am i supposed to use serverheader in !table component? (It gives error while used in a column)

5. Honestly you should update: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Placeholders

**Comment by CryptoMorin** [comment]
Searched a bit and
Got my answer for some

5. The one in config supports PlaceHolderAPI plugin
3. 1.2 already exists

**Comment by CodeCrafter47** [comment]
1. I'll consider adding a placeholder.

2. The food level placeholder is only available if [PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/) is installed. You can find more information about using placeholder from PlaceholderAPI on the following wiki page: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PlaceholderAPI
   
   Especially try the `/papi parse %player_food_level%` command to check whether PlaceholderAPI can resolve the placeholder. If it does, then you should be able to use `${viewer player_food_level}` in BungeeTabListPlus.
   
   I don't really want to create another placeholder built-in to BungeeTabListPlus if there is already one available when using PlaceholderAPI.

3. For all built-in placeholders that display a number you can use `x.y` (e.g. `${viewer vault_balance 1.2}`). The first number specifies how many digits to use at least, if the number has less digit you will see zero's at the front. The second number specifies the number of decimals. The dot and the second number may be omitted for whole numbers.
   
   Examples:
   `${playerset:global size 3}` -> `009`
   `${viewer balance 4.1}` -> `00.5`, `07.1`, `99.9` or `271.4`

4. Either use `serverSeparator: []` or even better remove the line entirely.

5. Custom placeholder configured in `config.yml` are available for use in all tab list configuration files. Those created in a tab list configuration file can only be used inside that file.

6. `serverHeader` can only be used inside a `!players_by_server` component. However you can use a `!players_by_server` component inside a `!table` component if that is what you want.
   
   Otherwise, if adding servers manually using the `!players` component inside the `!table` component as shown on the [wiki page about the table component](https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Configuration-Basics-Part-8---Fixed-Size-Tablist---Table), use just basic components to display the server names (as it's done on the wiki page I linked).

7. What should I change on the wiki page about placeholders?

**Comment by CryptoMorin** [comment]
Thank you,
All working fine and you should edit that PlaceHolder page about the 1.1 1.2 1.3 thing.
Also 1 more thing and i'm done!

I'm trying to make a placeholder that if player is both afk and vanished (yes it's possible) cancel 2 other existing placeholders that are used for the prefix in tablist and make a mix prefix. However i don't know how to hide other 2 placeholders that i made so only this one will display.
Here is the information needed:
`customPlaceholders:
  afk_tag:
    !conditional
    condition: ${player essentials_afk}
    true: '&8[&eAFK&8]'
    false: ''
  hidden_tag:
    !conditional
    condition: ${player is_hidden}
    true: '&8[&cH&8]'
    false: ''
  hiddenafk_tag:
    !conditional
    condition: ${player is_hidden} and ${player essentials_afk}
    true: '&8[&cH&7-&eAFK&8]'
    false: ''`

And the player component:
`playerComponent: "${hiddenafk_tag}${hidden_tag}${afk_tag}${player vault_prefix}${player name}"`

So it actually displays all the 3 placeholders, so is it possible to somehow cancel `${hidden_tag}` and `${afk_tag}` if `${hiddenafk_tag}` is true?

**Comment by CodeCrafter47** [comment]
The information about the number format isn't on the wiki because I don't really like the way it works. I don't have a better solution, so it's no going to change, so I might as well add the info to the wiki.

You could change the `afk_tag` placeholder so it only shows up if the player is not hidden by changing the condition to `${player essentials_afk} and ! $[player is_hidden}`.

**Comment by CodeCrafter47** [comment]
I decided against implementing a generic skin name placeholder in the 2.8.1 update. I still plan on adding it with the next big update.

**Comment by CryptoMorin** [comment]
Great then! Can't wait to hear from you soon!

Btw... As I'm friend with Kingdoms+ author, I decided to tell him to add support for BungeeTabList+ I hope he'll accept and you can start working on it!

**Comment by CodeCrafter47** [comment]
I got some questions regarding the skin name placeholder you asked for.

1. How did you set up SkinRestorer (installed on Bungee, Spigot or both)? Would you say that your setup is a common setup?
2. Since your concern is mainly about the name, what about the icon? Do you see the correct icon in the tab list when using another skin? Which icon does another player connected to a different server see on the tab list?

**Comment by CryptoMorin** [comment]
1.
The .jar supports both Spigot and Bungee. Yes I did put skins restorer in all of my servers (If you only put it in Bungee you must relog to apply skin changes, but if you install it on your spigot servers too it'll instantly change) - My setup isnt too much just some disabled skins and skin change cool down. The good thing is the plugin works without MySQL.

2.Honestly never tested BTLP on a premium server. But I would like the placeholders to be in ${viewer skin}.
But thought a little and some owners may like to use that in their ${viewer name} so yeah... It needs a separated placeholder.

Side note: I totally forgot but it seems like kingdoms+ already have some placeholders in PlaceholdersAPI. But if not I think the support must be from your side.

**Comment by CodeCrafter47** [comment]
A skin name placeholder is no longer planned.
