### ISSUE TITLE
Too many placeholders can cause lag?

### ISSUE THREAD

**Issue by MClausz** [CodeCrafter47/BungeeTabListPlus#268]
This is my tablist: https://pastebin.com/Uk4p5Yj1
Basically every player have around 40 placeholders.
Since I changed my tablist, the server usually have lag strike and I have to restart the Waterfall.
I'm using Waterfall, with around ~200 players and 4GB ram allocated to Waterfall.

**Comment by CodeCrafter47** [comment]
Using lots of placeholders should not be much of a problem, they scale pretty well with lots of players. In contrast to that player sets scale pretty bad with lots of players, computing them will eat up a lot of calculation power, sorting the players before displaying them even more so. The plugin only uses a single thread to update the tab list in order to prevent it from using up all CPU time, however if there is more work to do than it can do it may slowly fill up the RAM with scheduled task which can cause lag (more RAM can delay the issue but won't fix it). Player set performance is something I intend to improve.

**Comment by CodeCrafter47** [comment]
Player set performance has been improved with recent commits. If you find any other performance problems please open a new issue.
