### ISSUE TITLE
Premium Vanish + BTLP split seccond on tab issue.

### ISSUE THREAD

**Issue by MithrandirCraft** [CodeCrafter47/BungeeTabListPlus#283]
PremiumVanish version: 1.9.6
BungeeTabListPlus version: 2.8.1
Spigot version: 1.12.1
I have no error logs related to this issue.

I logged in to the network hub, switched server to Factions (Where the last time I logged of from that server, I was currently in vanish mode, which should be preserved as it is configured to act that way.)
Once I enter the server, I get an indicator telling me that I am vanished.
A player apparently sees me on the tab and says hello. I ask him how he knew I was there if I'm supposed to be vanished, and he says I appear for a split second before actually vanishing (I didn't even do anything, all I did was enter the server expecting to allready be vanished).

This happens occasionally and seemingly in a random fashion. Only with BTLP installed together with PV.

**Comment by CodeCrafter47** [comment]
This is due to the way PremiumVanish support is implemented in BungeeTabListPlus. When a player connects to a different server then BungeeTabListPlus asks the bridge plugin whether the player is vanished, the bridge plugin will eventually get the data from PremiumVanish and send it to BungeeTabListPlus. That of cause takes a small amount of time.

**Comment by MithrandirCraft** [comment]
![image](https://user-images.githubusercontent.com/6623704/50047790-e8bc0a80-00bc-11e9-9daa-1085ddf4d13a.png)

**Comment by MithrandirCraft** [comment]
Add an optional mode for considering all players as vanished before verification from premiumvanish?

**Comment by CodeCrafter47** [comment]
I'm not interested in adding this kind of work-around to the plugin. Especially since it would most likely involve creating a new config option which would break the tab list if changed by an uninformed user.

As I said before it should be possible to properly fix this:

> I think it should be possible for BungeeTabListPlus to communicate with the PremiumVanish BungeeCord plugin to figure out whether a player is vanished without a delay.

I'll try to include a fix for this issue with the next large update for BungeeTabListPlus.

Note to self: PremiumVanish BungeeCord API is located at <https://github.com/MyzelYam/PremiumVanishAPI>

**Comment by CodeCrafter47** [comment]
This issue has been fixed with the latest update.
