### ISSUE TITLE
BungeeTablistPlus and Pex whit mysql not Work

### ISSUE THREAD

**Issue by joeymaeuslp** [CodeCrafter47/BungeeTabListPlus#306]
I have the problem that the BungeeTablistPlus with Pex msql does not work because the plugin seems to be unable to read data from pex Msql the variable $ {player vault_prefix} does not work and will not be replaced with the prefix what can I ask you to look at my Permissions file is perfectly decorated

**Comment by CodeCrafter47** [comment]
This is not an issue in BungeeTabListPlus. BungeeTabListPlus doesn't even know PEX exists. All it does is to ask Vault for the prefix from the permission plugin. Since BungeeTabListPlus doesn't know anything about PEX, it can hardly be the fault of BungeeTabListPlus if one configuration of PEX works and another doesn't. The issue is in PEX or in the way you are using it (much more likely the latter). I haven't created PEX nor am I associated with it in any way, so I'm afraid I can't provide support for it.

**Comment by joeymaeuslp** [comment]
yes I understand that but synonymous but test your plugin yourself please times with mysql pex and you will see that it does not work then please write in the description of your plugin purely the btlp not working with pex mysql

**Comment by CodeCrafter47** [comment]
I'm pretty certain BungeeTabListPlus works just fine with PEX + MySQL. Not going to test it myself though. I think your issue is caused by not setting it up correctly (I can't help you to do that).
