### ISSUE TITLE
Duplicate Names in Tablist

### ISSUE THREAD

**Issue by doitliketyler** [CodeCrafter47/BungeeTabListPlus#332]
Hello. Every now and then even when players are offline their name remains in the tablist or even duplicates. Currently, there are only 3 players on but this is what the tablist looks like and it's ignoring the order:

https://imgur.com/a/KH7N3

There are 0 errors in the console and I'm using the latest version of BTLP. Any ideas?

**Comment by CodeCrafter47** [comment]
The duplicate players are probably caused by a bad plugin breaking BungeeCord (using AlwaysOnline by chance?). You'll probably also observe that the total player count displayed by the `/glist` command is too high.

The player order can be configured: <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PlayerOrder>.

**Comment by doitliketyler** [comment]
Funny you mention it...I am using AlwaysOnline. Is there a better alternative to it that you know of?

**Comment by doitliketyler** [comment]
Alright. Well, thanks for the info. I'm sure the order will resolve itself once it's removed. Cheers.
