### ISSUE TITLE
Overhead Pleyer's name can't hide with F1 key

### ISSUE THREAD

**Issue by watadora** [CodeCrafter47/BungeeTabListPlus#421]
Hi master,
I usually hide it for take a screenshot but can't it after introducing this plugin.
I tested starting Spigot without BungeeTabList Plus, it is OK.(can hiding)
I love BungeeTabListPlus ,so I wish its phenomenon will be fixed.
Thank you :)

**Comment by watadora** [comment]
P.S.
I tested it Spigot 1.13.2 #96 build with Waterfall #279 build,
and Spigot 1.13.2 #96 build with Bungeecord #1408 build.
I Produced BungeeTabListPlus all of them.

**Comment by CodeCrafter47** [comment]
In order to do what it does BungeeTabListPlus needs to assign every player to a scoreboard team. You and the other players being part of a scoreboard team causes the Minecraft client to ignore whether you've pressed F1 and render the name tag anyway. I think this is a bug in Minecraft. It's possible that 1.14 fixes this bug, but I haven't checked.

**Comment by CodeCrafter47** [comment]
Closing this as it is a bug in Minecraft, not this plugin.
