### ISSUE TITLE
Missing API specification with 1.14.

### ISSUE THREAD

**Issue by mibby** [CodeCrafter47/BungeeTabListPlus#436]
```
[13:22:54] [Server thread/WARN]: Plugin BungeeTabListPlus v2.8.12-SNAPSHOT does not specify an api-version.
```

**Comment by CodeCrafter47** [comment]
I think that's intentional.

**Comment by Andre601** [comment]
This can be ignored as it's more a notice, rather than an issue.
But the Bridge plugin could just have `api-version: 1.13` in the plugin.yml added without any negative impact on older servers. It would, however, tell Spigot to not use the legacy option for this plugin, meaning that if it uses code, that changed in 1.13 (e.g. Block and item names), that it would break.
