### ISSUE TITLE
tablist can not load .png files

### ISSUE THREAD

**Issue by nikissXI** [CodeCrafter47/BungeeTabListPlus#443]
![image](https://user-images.githubusercontent.com/31379266/62411923-535e8e00-b62d-11e9-8b26-ccedadd8466d.png)
![image](https://user-images.githubusercontent.com/31379266/62411959-c831c800-b62d-11e9-8d35-760c9539e956.png)

**Comment by CodeCrafter47** [comment]
This looks like a temporary fault on the client. Restarting it should fix the issue.

**Comment by Link0Darck** [comment]
Hello I have the same problem as the person but worse it doesn't display and I restarted my client but it doesn't matter.
`# This is the default configuration file of BungeeTabListPlus.
#
# Since the configuration of the plugin is quite complex you
# might want to have a look at the wiki from time to time.
# 
# Wiki: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki
#  Placeholders: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Placeholders
#  Examples: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Examples
#

# It is possible to have multiple tab list configuration files.
# BungeeTabListPlus will parse all .yml files it finds in the tabLists directory.
# Which tab list a player sees depends on the showTo and priority options.

# All player see this tab list
showTo: "all"

# Examples of alternative options for showTo:
# showTo: ' ${viewer server} == "Factions" '
# showTo: ' ${viewer server} == "Factions" or ${viewer server} == "Survival" '
# showTo: ' ${viewer vault_primary_group} == "Admin" '

# If after evaluating the showTo option of all tab list configs multiple tab lists
# are visible to a player, he will bw shown the one with the highest priority:
priority: 0

# Tab list header and footer:
showHeaderFooter: true

header:
- '&cBienvenue &f${viewer name}'
- '&eB&cienvenue &f${viewer name}'
- '&eBi&cenvenue &f${viewer name}'
- '&eBie&cnvenue &f${viewer name}'
- '&eBien&cvenue &f${viewer name}'
- '&eBienv&cenue &f${viewer name}'
- '&eBienve&cnue &f${viewer name}'
- '&eBienven&cue &f${viewer name}'
- '&eBienvenu&ce &f${viewer name}'
- '&eBienvenue &f${viewer name}'
- '&cB&eienvenue &f${viewer name}'
- '&cBi&eenvenue &f${viewer name}'
- '&cBie&envenue &f${viewer name}'
- '&cBien&evenue &f${viewer name}'
- '&cBienv&eenue &f${viewer name}'
- '&cBienve&enue &f${viewer name}'
- '&cBienven&eue &f${viewer name}'
- '&cBienvenu&ee &f${viewer name}'
- '&cBienvenue &f${viewer name}'

headerAnimationUpdateInterval: 0.2

footer:
- |-
  &6Neko-World Serveur minecraft 1.8.X - 1.10
  &eIP: play.neko-world.fr.nf
- |-
  &eNeko-World Serveur minecraft 1.8.X - 1.10
  &6IP: play.neko-world.fr.nf

footerAnimationUpdateInterval: 0.5

# Custom placeholders are a powerful mechanism to add more dynamic content
# to the tab list.
customPlaceholders:
  # Defines the ${afk_tag} placeholder which is used to add "|away"
  # to the players name if he is afk.
  afk_tag:
    !conditional
    condition: ${player essentials_afk}
    true: '&7|&o AFK'
    false: ''
  # Defines the ${viewer_colored_ping0} placeholder which displays the ping in green
  # if it is below 50ms, otherwise in yellow.
  viewer_colored_ping0:
    !conditional
    condition: "${viewer ping} < 50"
    true: "&a${viewer ping}"
    false: "&e${viewer ping}"
  # Defines ${the viewer_colored_ping} placeholder which displays the ping in red
  # if it is above 150ms, otherwise it is replaced with the ${viewer_colored_ping0}
  # placeholder ( < 50 -> green, > 50 -> yellow).
  # That results in the following color scheme:
  # 0 - 49   -> green
  # 50 - 149 -> yellow
  # 150+     -> red
  viewer_colored_ping:
    !conditional
    condition: "${viewer ping} < 150"
    true: ${viewer_colored_ping0}
    false: "&c${viewer ping}"

# Player sets are required to display players and player counts on the tab list.
# To display a player count use ${playerset:<name> size}, example: ${playerset:global size}.
playerSets:
  # The global player set contains all players
  global:
    filter: "true"
# # Some more examples. Be careful to get the number of spaces right when using them.
# # Player set containing all players on a specific server:
# survival:
#   filter: |-
#     ${player server} == "survival"
# # Player set containing all players on the same server as the player viewing the tab list:
# currentserver:
#   filter: |-
#     ${player server} == ${viewer server}
# # Player set containing all players on a specific server and world:
# survival_nether:
#   filter: |-
#     ${player server} == "survival"
#     and ${player world} == "world_nether"
# # Player set containing all admins:
# admins:
#   filter: |-
#     ${player vault_primary_group} == "Admin"
#     or ${player vault_primary_group} == "Fondateur"

# We want the tab list to have a fixed size of 60 slots.
# If you want a dynamic size you need to set type to DYNAMIC_SIZE
# and you don't need any of the options below it. Have a look at
# the example in the wiki to see which options you need instead:
# https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Examples#global-tab-list-dynamic-size
type: FIXED_SIZE
size: 60 # 60 slots -> 3 columns, 20 rows

# The defaultIcon and defaultPing will be used for all slots for which no other value is
# explicitely set.
defaultIcon: colors/dark_gray.png
defaultPing: 1000

# Here the content of the tab list is configured:
components:
# Three info slots at the top
- {text: "&cServeur: &6${viewer server}", icon: "default/server.png", ping: 0} # 1st row, 1st column
- {text: "&cGrade: &6${viewer vault_primary_group}", icon: "default/rank.png", ping: 0} # 1st row, 2nd column
# Show ping in different colors depending on how good/ bad it is
- {text: "&cPing: ${viewer_colored_ping}ms", icon: "default/ping.png", ping: 0} # 1st row, 3rd column
# A row of empty slots below
- {text: "", icon: "colors/dark_gray.png", ping: 1000} # 2nd row, 1st column
- {text: ""} # 2nd row, 2nd column; Since icon and ping are the default they don't need to be specified explicitely.
- {} # 2nd row, 3rd column; Since the text is empty it doesn't need to be specified either
# The players by server component adds players to the tab list grouped by server
- !players_by_server
  # The global player set is configured above
  playerSet: global
  # The server header is shown for each server above the players on that server.
  # We use it to display the server name and the player count.
  serverHeader:
  - {text: "&e&n${server}&f&o (${server_player_count}):", icon: "colors/yellow.png", ping: 0}
  # The server separator is shown between two consecutive servers. 
  # Here it use used to separate the servers with an empty row of slots, showing two more variants to display an empty slot.
  serverSeparator:
  - {}
  - ""
  -
  # Whether empty servers should show up too
  showServers: ALL
  # Format of the player slot. Add prefixes as you like
  playerComponent: "${player name}${afk_tag}"
  # If there isn't enough space for all players the morePlayersComponent is displayed. We use to to display the number of players which couldn't be displayed on the tab list.
  morePlayersComponent: {text: "&7... and &e${other_count} &7others", icon: "colors/gray.png", ping: 0}
# A spacer creates as many empty slots as possible.
- !spacer {}
# Because the spacer has eaten up all the remaining free slots, the nine slots below are guaranteed to be at the bottom of the tab list.
# Let's start with another empty row
- "" # 18th row, 1st column
- "" # 18th row, 2nd column
- "" # 18th row, 3rd column
# Then some nice animations at the bottom
- !animated # 19th row, 1st column
  interval: 0.2
  components:
  - {text: "&6&c=&6==============", icon: "colors/gold.png", ping: 0}
  - {text: "&6=&c=&6=============", icon: "colors/gold.png", ping: 0}
  - {text: "&6==&c=&6============", icon: "colors/gold.png", ping: 0}
  - {text: "&6===&c=&6===========", icon: "colors/gold.png", ping: 0}
  - {text: "&6====&c=&6==========", icon: "colors/gold.png", ping: 0}
  - {text: "&6=====&c=&6=========", icon: "colors/gold.png", ping: 0}
  - {text: "&6======&c=&6========", icon: "colors/gold.png", ping: 0}
  - {text: "&6=======&c=&6=======", icon: "colors/gold.png", ping: 0}
  - {text: "&6========&c=&6======", icon: "colors/gold.png", ping: 0}
  - {text: "&6=========&c=&6=====", icon: "colors/gold.png", ping: 0}
  - {text: "&6==========&c=&6====", icon: "colors/gold.png", ping: 0}
  - {text: "&6===========&c=&6===", icon: "colors/gold.png", ping: 0}
  - {text: "&6============&c=&6==", icon: "colors/gold.png", ping: 0}
  - {text: "&6=============&c=&6=", icon: "colors/gold.png", ping: 0}
  - {text: "&6==============&c=&6", icon: "colors/gold.png", ping: 0}
- !animated # 19th row, 2nd column
  interval: 0.2
  components:
  - {text: "&6&c=&6==============", icon: "colors/gold.png", ping: 0}
  - {text: "&6=&c=&6=============", icon: "colors/gold.png", ping: 0}
  - {text: "&6==&c=&6============", icon: "colors/gold.png", ping: 0}
  - {text: "&6===&c=&6===========", icon: "colors/gold.png", ping: 0}
  - {text: "&6====&c=&6==========", icon: "colors/gold.png", ping: 0}
  - {text: "&6=====&c=&6=========", icon: "colors/gold.png", ping: 0}
  - {text: "&6======&c=&6========", icon: "colors/gold.png", ping: 0}
  - {text: "&6=======&c=&6=======", icon: "colors/gold.png", ping: 0}
  - {text: "&6========&c=&6======", icon: "colors/gold.png", ping: 0}
  - {text: "&6=========&c=&6=====", icon: "colors/gold.png", ping: 0}
  - {text: "&6==========&c=&6====", icon: "colors/gold.png", ping: 0}
  - {text: "&6===========&c=&6===", icon: "colors/gold.png", ping: 0}
  - {text: "&6============&c=&6==", icon: "colors/gold.png", ping: 0}
  - {text: "&6=============&c=&6=", icon: "colors/gold.png", ping: 0}
  - {text: "&6==============&c=&6", icon: "colors/gold.png", ping: 0}
- !animated # 19th row, 3rd column
  interval: 0.2
  components:
  - {text: "&6&c=&6==============", icon: "colors/gold.png", ping: 0}
  - {text: "&6=&c=&6=============", icon: "colors/gold.png", ping: 0}
  - {text: "&6==&c=&6============", icon: "colors/gold.png", ping: 0}
  - {text: "&6===&c=&6===========", icon: "colors/gold.png", ping: 0}
  - {text: "&6====&c=&6==========", icon: "colors/gold.png", ping: 0}
  - {text: "&6=====&c=&6=========", icon: "colors/gold.png", ping: 0}
  - {text: "&6======&c=&6========", icon: "colors/gold.png", ping: 0}
  - {text: "&6=======&c=&6=======", icon: "colors/gold.png", ping: 0}
  - {text: "&6========&c=&6======", icon: "colors/gold.png", ping: 0}
  - {text: "&6=========&c=&6=====", icon: "colors/gold.png", ping: 0}
  - {text: "&6==========&c=&6====", icon: "colors/gold.png", ping: 0}
  - {text: "&6===========&c=&6===", icon: "colors/gold.png", ping: 0}
  - {text: "&6============&c=&6==", icon: "colors/gold.png", ping: 0}
  - {text: "&6=============&c=&6=", icon: "colors/gold.png", ping: 0}
  - {text: "&6==============&c=&6", icon: "colors/gold.png", ping: 0}
- {text: "&cHeure: &6${time H:mm:ss}", icon: "default/clock.png", ping: 0} # 20th row, 1st column
- {text: "&cJoueurs: &6${playerset:global size}", icon: "default/players.png", ping: 0} # 20th row, 2nd column
- {text: "&cArgent: &6${viewer vault_balance 1.2}", icon: "default/balance.png", ping: 0} # 20th row, 3rd column`
[https://imgshare.io/images/2020/02/20/2020-02-21_04.33.02.png](url)

**Comment by CodeCrafter47** [comment]
Your issue is different. You are not seeing the icons at all. The reason is that your server is running in offline mode. See #269.

**Comment by Link0Darck** [comment]
> Votre problème est différent. Vous ne voyez pas les icônes à tous. La raison en est que votre serveur est en cours d'exécution en mode hors connexion. Voir #269.
thank very much for you help
