### ISSUE TITLE
No Hat layer (Known cause)

### ISSUE THREAD

**Issue by sanjay900** [CodeCrafter47/BungeeTabListPlus#50]
BungeeTabListPlus doesn't seem to render the hat layer. This is caused by the fact that minecraft relies on an entity being spawned with the hat DataWatcher enabled to work. When i create a npc with the same name as a tab, and set DataWatcher 10 on it to (byte)127, i get hats. I managed to make a really buggy version of BungeeTabListPlus that rendered hats, and ill look into uploading it tomorrow.

**Comment by sanjay900** [comment]
![image](https://cloud.githubusercontent.com/assets/1862720/9958685/94082f48-5e60-11e5-8c6c-acb125b13ce9.png)
Ive managed to make my version semi stable, it does spawn a player per tab at 0,0,0, but it makes that player invisible.

**Comment by sanjay900** [comment]
https://github.com/sanjay900/BungeeTabListPlus

**Comment by CodeCrafter47** [comment]
Your version looks a bit hacky. I think it will still take some time until support for the hat layer is added to this plugin. For something like this to be added the following things need to be thought about.
- [ ] where to spawn the fake players. Probably it is possible to spawn them outside of the world border, so no-one will ever see them
- [ ] whether hat layer is shown or not should be configurable for custom slots, otherwise the setting of the player should be used
- [ ] one needs to think about which entity ids to use to avoid collisions
- [ ] also needs to work with 1.9 (when it comes out)
- [ ] not sending packets to pre 1.8 clients (removing tablist support for pre 1.8 clients is not an option)
This isn't really a priority for me so I won't make add it myself any time soon. Still if you like feel free to further experiment with the plugin.

Some things: If you wouldn't reformat my code it would be easier to view the changes. Not reformatting also makes it easier to merge my latest changes. Also your modified version might be more stable if you wouldn't remove huge parts of my code.

**Comment by sanjay900** [comment]
Yeah, i was using a modified version without team packets, because it was
annoying me that they didn't work. I wasn't expecting you to merge it in,
just showing that it was possible. Im just spawning them at 0,0,0 and
making them invisible, then you don't see them. Im using these entity ids
for something else and it wasn't colliding, but i think a few others might
use the same trick, so you would have to track entity spawning or work out
something else. My version is pretty stable for what i do atm though, so
its okay for now.

**Comment by sanjay900** [comment]
The version i just pushed is up to date/merged and i found a way around what i was doing, so it has no code removed either.

**Comment by sanjay900** [comment]
[x] where to spawn fake players - I just make them invisible, so people won't see them anyways.
[x] whether hat layer is shown - I just added a boolean to slot to make it configurable, otherwise, it should be pulled from the player since it shouldn't be spawning a npc for existing players
[ ] Im currently using Short.MIN_VALUE+the row, which seems to work, although its possible others are using this hack, so it might need a bit of thought
[ ] 1.9 - Have to worry more about this when it releases
[ ] <1.8 - It should work since all the sending code is done in 1.8 only tablists

**Comment by CodeCrafter47** [comment]
Looks much better than last time now, but still a bit hacky.

I'm not convinced of spawning invisible players since spectator mode players can see them.

You screwed up the code formatting and imports order at some places.

Your code will break with 1.9. It is right we don't know all the changes that will happen until the release but I would prefer it if the plugin would just continue to work. A solution would be to simply disable the head layer for 1.9 clients at first.

Your code should somehow allow for the head layer to be disabled after it was enabled for a slot. Something like that can happen on reload or if players change positions in the tab list. Sometimes (always if tab size is 80) the tab list plugin uses a fake player for a player slot. In that case the head layer is not shown correctly.

In TabList18 your code will send the skin of a player to the client again if the head layer was enabled. This causes unnecessary traffic. Each skin blob is about 1k.

In TabList18v3 your code can cause the plugin to change the skin of a real player. This is bad.

Also all spawned players should be removed if unload() is called.
