### ISSUE TITLE
internal error occurred

### ISSUE THREAD

**Issue by Chynoah** [CodeCrafter47/BungeeTabListPlus#54]
Hey there =)
at the first sorry for my very bad english -.-' 

i had updated the plugin for a few minutes, cause the plugin doesn't run and the tablist was the original from minecraft. now i had updated and i have a internal error, this spams my consol xDD 
before i had update the plugin, the config and the layout and all was work, but not now :/
when i do the original tablist default.yml from the plugin on the server, the plugin works. but when i do my own tablist yml an error occurred. but i wouldn't my configurated tablist do new :((

can you help me? here is the error: http://pastebin.com/NEcVWhL7
here is my configurated tablist yml: http://pastebin.com/h8ctU0hQ

thanks for help :)

**Comment by CodeCrafter47** [comment]
The happens because the plugin now checks the layout more strictly. And yours just doesn't fit in the tablist.

You config has three [ROW=18] assignments. The plugin puts the first one in the first column then the seconds one in the second column and the third one in the third column. Assuming your tab_size is 80 there is basically one column left. But in your config you have four [ROW=0] assignments next. But row 0 is only available one time in the one column left. So the plugin can't find enough space in the tablist which causes this error.
