### ISSUE TITLE
PlaceholderAPI placeholders no longer working.

### ISSUE THREAD

**Issue by funnycubeguy** [CodeCrafter47/BungeeTabListPlus#565]
They used to work until I updated to the latest. None of my placeholders work and I get messages in my log about them - except these are valid placeholderapi placeholders.

> WARNING: Placeholder 'luckperms_prefix' has been deprecated. Use 'luckpermsbungee_prefix' instead.
> in use of placeholder ${player luckperms_prefix}
> in 'reader', line 4607, column 18:
> playerComponent: "${player luckperms_meta_pin}${p ...

`
playerComponent: "${player luckperms_meta_pin}${player luckperms_prefix} ${player luckperms_meta_color}${player cmi_user_display_name}"`

luckpermsbungee_prefix doesn't help me since my permissions are not luckperms bungee permisisons. they are server permissions. the bungee server has a different set of permissions of admins only. i do not want to combine all of my servers and permissions to one bungee instance.

luckperms_meta_ and luckperms_prefix are placeholder api placeholders

**Comment by CodeCrafter47** [comment]
`luckperms_prefix` is a built-in placeholder. Unfortunately it is named the same a the PlaceholderAPI placeholder which prevents you from using that one. To fix this issue the built-in `luckperms_prefix` has been renamed to `luckpermsbungee_prefix`. Since I don't want to break people's configs with the update `luckperms_prefix` will still use the built-in placeholder. However, the plugin tells you about the name change, so you can adapt your config, since in the future `luckperms_prefix` will no longer use the built-in placeholder.

Regarding the other PlaceholderAPI placeholders, the warnings you are getting in the log might be false positives. Please join the server and see if they actually work. If they do the warnings will no longer show on the next reload/ restart.

**Comment by funnycubeguy** [comment]
> `luckperms_prefix` is a built-in placeholder. Unfortunately it is named the same a the PlaceholderAPI placeholder which prevents you from using that one. To fix this issue the built-in `luckperms_prefix` has been renamed to `luckpermsbungee_prefix`. Since I don't want to break people's configs with the update `luckperms_prefix` will still use the built-in placeholder. However, the plugin tells you about the name change, so you can adapt your config, since in the future `luckperms_prefix` will no longer use the built-in placeholder.
> 
> Regarding the other PlaceholderAPI placeholders, the warnings you are getting in the log might be false positives. Please join the server and see if they actually work. If they do the warnings will no longer show on the next reload/ restart.

This completely breaks any of the other luckperms placeholders. Now I have to downgrade to an old version for luckperms_meta to work. Wish you kept it the way things were.

**Comment by CodeCrafter47** [comment]
You can use `vault_prefix` to get the prefix from the spigot server.
