### ISSUE TITLE
Player list head patch

### ISSUE THREAD

**Issue by xeq** [CodeCrafter47/BungeeTabListPlus#61]
The TabList looks normally on Minecraft 1.8, but when someone joins the server, one of the heads (bottom right) becomes replaced by his head. Can you fix it? It's really annoying.

**Comment by CodeCrafter47** [comment]
Since Minecraft 1.8 every player on a Minecraft server must also be displayed in the tab list. Which forces BungeeTabListPlus to make the skin of every player on the same spigot server appear somewhere in the tab list. If you have configured the tab list to show at least all the players on the same server you won't notice this limitation as it will put the skin of the player beneath the players name where you expect it anyway. However for all players which are not configured to appear on the tab list it will put their skins on the bottom right as that is the place where I consider a wrong skin to be least annoying.

A way to work around this limitation is to set the tab_size to 80. The Minecraft client will not display more than 80 slots. This allows BungeeTabListPlus to move the tab list entries of players which are not configured to appear on the tab list to (for example) slot 81. That way the players are in the tab list which prevents glitches like players randomly becoming invisible or having the wrong skin, but on the other hand the client won't display these "unwanted" players in the tab list, so the tab list appears to be correct.
