### ISSUE TITLE
Problems and Suggestions about fakePlayers

### ISSUE THREAD

**Issue by 778563781** [CodeCrafter47/BungeeTabListPlus#62]
Hello, I come from China, I really like your plugin .
  I think feedback to give you a advice about fakeplayers.I can only use fakeplayers in version 2.0#4, can't be used after the upgrade to the latest version.
  There will be a mistake!And you may add to display the number of fakeplayers on Bungeecord motd, perfect just the way they are.
  My English is not very good, hope you can understand.
  My e-mail ：12345@mcwyg.com

**Comment by CodeCrafter47** [comment]
I believe the issue you are experiencing has already been fixed in the latest dev-build. See #59 .

The fakePlayers feature has been created to assist me with testing the plugin, and so I can make screen-shots of the tab list with a lot of players for the documentation. It is not there to boost the player count of servers. Thus there is no need for the fake players to appear anywhere else but in the tab list.

**Comment by 778563781** [comment]
But in China, the number of online is really important.Your plugin fakeplayers can simulate a false number online, really good.I really want to use this feature, want to provide a method of use, if the wrong is my words.QAQ

**Comment by CodeCrafter47** [comment]
Closing this issue as the bug has been fixed and the presented suggestion is outside the scope of this plugin.
