### ISSUE TITLE
Randomly stopped working

### ISSUE THREAD

**Issue by OwlmanMC** [CodeCrafter47/BungeeTabListPlus#622]
My tablist randomly stopped working and when I try to reload the plugin I get this error

`[BungeeTabListPlus]: Failed to load tab list configuration file plugins/BungeeTabListPlus/tabLists/default.yml.
Cannot create property=playerOrder for JavaBean=de.codecrafter47.taboverlay.config.dsl.RectangularTabOverlayTemplateConfiguration@12bb5e
 in 'reader', line 1, column 1:
    showTo: all
    ^
Unable to find property 'playerOrder' on class: de.codecrafter47.taboverlay.config.dsl.RectangularTabOverlayTemplateConfiguration
 in 'reader', line 81, column 14:
    playerOrder: vault_primary_group custom Own
                 ^
`

**Comment by CodeCrafter47** [comment]
There is an error in the `default.yml` configuration file. Please upload the file here, so I can have a look at it.

**Comment by OwlmanMC** [comment]
Sorry I didn't get a email. Here is the file with some stuff replaced with Xes to hide IP's
https://pastebin.com/2c8YXtL2

**Comment by CodeCrafter47** [comment]
Sorry for the (very) late answer, I missed this somehow. I case you're still looking for a solution, or if someone else stumbles across this, the issue is the `playerOrder` option. It doesn't go at the top level of the config. Instead it needs to be added to each `!players` component. After making that change your config file looks like this: <https://pastebin.com/nnxcveEG>.

**Comment by OwlmanMC** [comment]
Hey, thanks for reaching out! I eventually figured it out that is was the player order and forgot to close this. I really appreciate that I got some kind of response for anyone who is also having this problem.
