### ISSUE TITLE
Clients get sent wrong UUID

### ISSUE THREAD

**Issue by killjoy1221** [CodeCrafter47/BungeeTabListPlus#79]
The UUID of others is important to the client. It's used for things such as determining if a player is wearing a hat when rendering the tab list. It's also used to check if another player is a spectator and render them accordingly.

I also maintain a mod that heavily depended on the uuids being correct (I now extract the uuid from the texture info).

Looks like it's being done here. Though I understand why you're doing it, it messes things up for the client. https://git.io/vg4Kx https://git.io/vg4ih

Also summoning our admin @shroomdog27

**Comment by killjoy1221** [comment]
Here's a screenshot of the spectator mode. On the right is myself. On the left is another player. We are both in spectator mode.
![](http://i.imgur.com/ETDoqxV.png)

**Comment by CodeCrafter47** [comment]
The plugin will always send one slot in the tab_list with the correct uuid, username and skin for each player on the same server. This is required so ingame skins are rendered correctly. In some cases that slot will be the same where the players name is displayed in the tab list and in some cases it will be a different slot. The first happens for most players if tab_size is lower than 80. If tab_size is set to 80 the slots with the correct uuid, username and skin won't be visible because they will not be with the 80 slots the client can display.

I don't care much about the head layer in the tab_list as that is even bugged on a vanilla server, because the client only renders the heads layer if a player entity is spawned for that player.

I'm aware of the issue with the spectator mode. The plugin doesn't tell the client if other players are in spectator mode. That is because spectator mode players will always be at the bottom right of the tab list which I don't want. However there aren't any negative effects of spectator mode players being rendered in a different way.

I believe that extracting the uuid from the texture info might be a bad idea depending on your use case. That is because the plugin allows for a texture to be used for multiple slots. Depending on your configuration you can also make the plugin not use the players texture for the slot where it displays the players name.

The fake player slots are created to create a fixed size tab list thus allowing for adding custom text slots to the tab list. The plugin will prefer using the fake player slots instead of ones with correct uuid.

You can however use the following patch: [http://pastebin.com/cnjieT5k](http://pastebin.com/cnjieT5k) to make the plugin use the correct uuids for all players on the same server. Using that patch the plugin will use scoreboard teams to maintain the correct order of the slots. That is basically what the plugin does if you set tab_size to a value lower than 80.

**Comment by CodeCrafter47** [comment]
I think the question here has been answered.
