### ISSUE TITLE
BungeeTabListPlus breaks Team collision

### ISSUE THREAD

**Issue by hurrgurl** [CodeCrafter47/BungeeTabListPlus#90]
Our plugin is relying on org.bukkit.scoreboard.Team (there is a collision rule) to completely remove player collision in 1.9 by adding all players to teams. Adding BungeeTabListPlus breaks this functionality for some reason. Could there be an explanation or a fix?

**Comment by CodeCrafter47** [comment]
The fix is to set tab_size to 80.

If the tab_size is lower than 80 (like in your case) then BungeeTabListPlus uses scoreboard teams to sort the slots in the tab list. This prevents other plugins from using scoreboard teams. If BungeeTabListPlus detects another plugin using scoreboard teams it will print a warning to the bungeecord console.

**Comment by connection-lost** [comment]
@CodeCrafter47 Can you elaborate why BungeeTabListPlus will use a different mechanic if tab_size is lower than 80?
tab_size = 80 looks ugly sometimes :(

**Comment by CodeCrafter47** [comment]
In Minecraft 1.8 there have been some changes to how the tab list works. Now the client will sort all tab list entries alphabetically, the client will display up to 80 tab list entries and each player is required to have a tab list entry.

The client sorting the tab list entries alphabetically is obviously bad for BungeeTabListPlus. But if tab_size is set to 80 this is not really a problem, because each tab list entry has two names (an internal name used for sorting the entries, and the display name that is actually shown in the tab list). So BungeeTabListPlus just sends 80 tab list entries and chooses their internal name in a way that the client will show them before any other entries. Since the client only shows up to 80 tab list entries you won't notice the others. Remember: there has to be one tab list entry for each player.

If tab size is lower than 80 then the fact that there has to be a tab list entry for each player will become a problem, because these tab list entries will have the internal name set to the name of the player and will have the skin of the player. Fortunately the Minecraft client offers a second way of sorting tab list entries: It sorts the entries by the name of the scoreboard team they have been assigned to. By assigning a scoreboard team to each player and to each tab list entry that does not belong to a player BungeeTabListPlus can change the order of the tab list entries. It will do that to move all the player entries that must exist to the place where you want these players to appear in the tab list.

**Comment by sanjay900** [comment]
Could you make an API for controlling teams on internal players?
