### ISSUE TITLE
Mixed Tablist

### ISSUE THREAD

**Issue by FireF0re** [CodeCrafter47/BungeeTabListPlus#93]
![2016-03-30_13 16 53](https://cloud.githubusercontent.com/assets/10896804/14140618/66432dda-f67a-11e5-8a63-13c3c92ee463.png)

Next problem :( The tablist is mixing when someone goes to another server.
Thanks for help

**Comment by CodeCrafter47** [comment]
Which version of BungeeTabListPlus and BungeeCord are you using?

**Comment by FireF0re** [comment]
BungeeCord: git:BungeeCord-Bootstrap:1.9-SNAPSHOT:aaddc9f:1135
BungeeTabListPlus: 2.4.3

**Comment by CodeCrafter47** [comment]
Can you check whether ffcde53a3cf0c28eacd8780b2f86b179b503fa2d fixed that?

You can get a build with that commit from my jenkins: http://ci.codecrafter47.dyndns.eu/job/BungeeTabListPlus/

**Comment by FireF0re** [comment]
It's always the same :( it's most by the player who came at last to the citybuild server. When a new player come to citybuild it's mostly correct.

**Comment by FireF0re** [comment]
Ah, I have found the problem. It's Citizens. I have deletet it and all is okay. :D

**Comment by Leiath** [comment]
I had the same problem with my tab listings, disabled citizens and it all works as it should.

**Comment by PsychoLynx** [comment]
The issue seems mostly gone in build 493 of BungeeTabListPlus and latest Citizens. An interesting tidbit I found out is that now it seems to me that only being near an NPC that shares a name with you (For example, me going near an NPC called "PsychoLynx" will cause this to happen: http://imgur.com/tEXuXdb 

After renaming the NPC and switching servers back and forth, the issue stopped. Interestingly enough, you can add a color code to the NPC's name to stop the tablist from bugging out, but I'd rather not go through all of our server's NPCs as a workaround solution.
